apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-app-deployment
  namespace: oneapp-nonprod-ns
spec:
  selector:
    matchLabels:
      app: one-app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: one-app
        version: "1.0"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: one-app-container
        image: mukhlisaji/one-app:latest
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: dockerhub